require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3

Metrics/ParameterLists:
  Max: 6

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/*/features/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'apps/*/application.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

RSpec/ExampleLength:
  Max: 10
