require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3

Metrics/ParameterLists:
  Max: 6

Layout/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/*/features/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'apps/*/application.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

RSpec/ExampleLength:
  Max: 10

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
