version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          HANAMI_ENV: test
      - image: circleci/postgres:11.2-alpine-ram
        environment:
          POSTGRES_USER: slackerduty
          POSTGRES_PASSWORD: slackerduty
      - image: redis


    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: bundle
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: sudo apt-get update
      - run: sudo apt-get install -y postgresql-client

      - run:
          name: hanami db prepare
          command: bundle exec hanami db prepare
      - run:
          name: rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob spec/**/*_spec.rb | circleci tests split --split-by=timings)"
            bundle exec rspec \
              --format documentation \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: rubocop
          command: bundle exec rubocop -p
